version: "3"

services:
  nuxt:
    build: .
    container_name: aladarbi-website
    restart: always
    ports:
      - "3000"
    command:
      "npm run start"

  nginx:
    image: nginx:1.13
    container_name: vuevixens-nginx
    ports:
      - "3006:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt